# Use official Python lightweight image

FROM python:3.10-slim

#Set the working directory inside the container
WORKDIR /app

# Prevent Python from writing .pyc files and buffer stdout
ENV PYTHONDONTWRTIEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies required for ML packages 

RUN apt-get update && apt-get install -y --no-install-recommends \
   build-essential \
   && rm -rf /var/lib/apt/lists/*

# Copy dependencies and install
COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the actual application code
COPY api/ ./api/
COPY src/ ./

# We will mount data/ and mlops_artifacts/ at runtime via docker-compose

#Expose the FastAPI port 
EXPOSE 8000

# Command to run the Enterprise API

CMD ["uvicorn","api.main:app","--host","0.0.0.0","--port","8000"]