version: '3.8'

services:
  nexus-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nexus-backend-api
    ports:
      - "8000:8000"
    volumes:
      # Mount local data and artifacts so the API has access to live CSVs and trained models
      - ./data:/app/data
      - ./mlops_artifacts:/app/mlops_artifacts
    restart: unless-stopped
    networks:
      - nexus-net

  nexus-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: nexus-frontend-ui
    ports:
      - "8501:8501"
    environment:
      # Tells the Streamlit container how to find the API container over the Docker network
      - NEXUS_API_URL=http://nexus-api:8000
    volumes:
      # Mount local data so UI can generate drop-downs and charts
      - ./data:/app/data
    depends_on:
      - nexus-api
    restart: unless-stopped
    networks:
      - nexus-net

networks:
  nexus-net:
    driver: bridge