import pandas as pd

class FeatureEngineering:
    """Core Quantitative Indicators Engine"""
    @staticmethod
    def engineer_features(df):
        df = df.copy()
        # Drop any empty trailing rows (common in live data APIs like yfinance)
        if 'Close' in df.columns:
            df = df.dropna(subset=['Close'])
        # Ensure we have datetime index
        if 'Date' in df.columns:
            df = df.set_index('Date')
            
        df['Daily_Return'] = df['Close'].pct_change()
        df['MA_20'] = df['Close'].rolling(window=20).mean()
        df['MA_50'] = df['Close'].rolling(window=50).mean()
        df['Volatility_20'] = df['Daily_Return'].rolling(window=20).std()
        
        # Bollinger Bands
        df['BB_Upper'] = df['MA_20'] + (df['Close'].rolling(window=20).std() * 2)
        df['BB_Lower'] = df['MA_20'] - (df['Close'].rolling(window=20).std() * 2)
        
        # MACD & Signal Line
        exp1 = df['Close'].ewm(span=12, adjust=False).mean()
        exp2 = df['Close'].ewm(span=26, adjust=False).mean()
        df['MACD'] = exp1 - exp2
        df['Signal_Line'] = df['MACD'].ewm(span=9, adjust=False).mean()
        
        # VWAP (Volume Weighted Average Price)
        df['VWAP_20'] = (df['Close'] * df['Volume']).rolling(20).sum() / df['Volume'].rolling(20).sum()
        
        # RSI 14
        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / (loss + 1e-9) # prevent division by zero
        df['RSI_14'] = 100 - (100 / (1 + rs))
        
        # Stochastic RSI
        min_rsi = df['RSI_14'].rolling(14).min()
        max_rsi = df['RSI_14'].rolling(14).max()
        df['Stoch_RSI'] = (df['RSI_14'] - min_rsi) / (max_rsi - min_rsi + 1e-10)
        
        # Fill NaNs generated by rolling windows with 0 or bfill
        df = df.bfill().fillna(0)
        return df